### ISSUE TITLE
Documentation completeness checklist

### ISSUE THREAD

**Issue by tfuxu** [GradienceTeam/docs#1]
#### Documentation essentials:
- [x] Installation and build instructions (mostly copied from [`HACKING.md`](https://github.com/GradienceTeam/Gradience/blob/main/HACKING.md))
- [x] First setup
- [x] Usage / How to use Gradience
- [ ] Troubleshooting
- [x] CLI usage
- [ ] FAQ? (I think that Troubleshooting section will mostly cover what would be in FAQ)

##### Additional things to do:

- [ ] Remove contents list from home page and make it more inviting to user
- [ ] Add warning in `Installation` section about Flatpak being the only officially supported install option
- [ ] Update `First setup` section from the original README design 
- [ ] Split Usage section into smaller pages the same way how it's done in GNOME HIG documentation ([example](https://developer.gnome.org/hig/guidelines.html))

**Comment by daudix** [comment]
Here is initial troubleshooting page, written in markdown as I'm not familiar with the RTD docs format

[:paperclip: trouble.md](https://github.com/GradienceTeam/Docs/files/11241106/trouble.md)

**Comment by tfuxu** [comment]
> Here is initial troubleshooting page, written in markdown as I'm not familiar with the RTD docs format
> 
> [trouble.md](https://github.com/GradienceTeam/Docs/files/11241106/trouble.md)

Apart from a few grammatical errors, it looks good, has most currently known solutions for the top popular issues and is nicely formatted. I'll fix those mistakes and port it to `*.rst`. Only one thing that is missing in this draft, are some screenshots, but I can add them myself when I'll port your document to rst. 

Also, check out [Quick reStructuredText](https://docutils.sourceforge.io/docs/user/rst/quickref.html) if you want to quickly learn how to use rst.

**Comment by daudix** [comment]
_Ah yes, the grammatical errors, love them…_

Thanks for the rst guide! At first glance it seems to be similar to markdown, so it will be easier to understand
